### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by Lemuli** [AnkitSharma-007/Blazor-Computer-Vision-Azure-Cognitive-Services#1]
Hello,sir

       According to your code, I reported the following error when I went to execute it. Please see below
![image](https://user-images.githubusercontent.com/37833120/143767544-f459dd41-5232-43b6-b1b0-ed875e2fed3d.png)
![image](https://user-images.githubusercontent.com/37833120/143767388-3e45c2f8-2bd1-4d97-9123-39241a126e9d.png)

**Comment by AnkitSharma-007** [comment]
This is a null reference exception. It is not possible for me to provide a solution by just looking at the SS. Try to debug and find why the `ocrResult` object is null. Your API key might be wrong. Check that too.
